# Generated by Django 5.1.2 on 2024-11-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=100)),
                ('question_text', models.CharField(max_length=500)),
                ('pub_date', models.DateField(verbose_name='date published')),
            ],
        ),
    ]
