# Generated by Django 5.1.2 on 2024-11-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='question_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='question_title',
            new_name='title',
        ),
    ]
