# Generated by Django 5.1.2 on 2024-11-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_options_post_if_edited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edited_at',
            field=models.DateTimeField(null=True),
        ),
    ]
